name: NodeJS with Gulp

on:
  push:
    branches: [ "module-bundler-1" ]
  pull_request:
    branches: [ "module-bundler-1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: start-dev
      run: |
        npm run start-dev
        
